export const HUB_METHODS = {
  // Client → Server
  SEND_MESSAGE: "SendMessage",
  MAKE_OFFER: "MakeOffer",
  RESPOND_TO_OFFER: "RespondToOffer",
  PROPOSE_MEETING: "ProposeMeeting",
  RESPOND_TO_MEETING: "RespondToMeeting",
  SHARE_AVAILABILITY: "ShareAvailability",
  RESPOND_TO_AVAILABILITY: "RespondToAvailability",
  CANCEL_MEETING: "CancelMeeting",
  CANCEL_AVAILABILITY: "CancelAvailability",
  // Server → Client
  RECEIVE_MESSAGE: "ReceiveMessage",
  UPDATE_UNREAD_COUNT: "UpdateUnreadCount",
  OFFER_MADE: "OfferMade",
  OFFER_ACCEPTED: "OfferAccepted",
  OFFER_DECLINED: "OfferDeclined",
  OFFER_COUNTERED: "OfferCountered",
  OFFER_EXPIRED: "OfferExpired",
  MEETING_PROPOSED: "MeetingProposed",
  MEETING_ACCEPTED: "MeetingAccepted",
  MEETING_DECLINED: "MeetingDeclined",
  MEETING_RESCHEDULED: "MeetingRescheduled",
  MEETING_EXPIRED: "MeetingExpired",
  MEETING_CANCELLED: "MeetingCancelled",
  AVAILABILITY_SHARED: "AvailabilityShared",
  AVAILABILITY_RESPONDED: "AvailabilityResponded",
  AVAILABILITY_EXPIRED: "AvailabilityExpired",
  AVAILABILITY_CANCELLED: "AvailabilityCancelled",
  // Contract card — Client → Server
  REQUEST_CONTRACT: "RequestContract",
  RESPOND_TO_CONTRACT: "RespondToContract",
  CANCEL_CONTRACT: "CancelContract",
  SUBMIT_CONTRACT_SELLER_FORM: "SubmitContractSellerForm",
  SUBMIT_CONTRACT_BUYER_FORM: "SubmitContractBuyerForm",
  // Contract card — Server → Client
  CONTRACT_REQUESTED: "ContractRequested",
  CONTRACT_STATUS_UPDATED: "ContractStatusUpdated",
} as const;
