export const HUB_METHODS = {
  // Client → Server
  SEND_MESSAGE: 'SendMessage',
  MAKE_OFFER: 'MakeOffer',
  RESPOND_TO_OFFER: 'RespondToOffer',
  PROPOSE_MEETING: 'ProposeMeeting',
  RESPOND_TO_MEETING: 'RespondToMeeting',
  SHARE_AVAILABILITY: 'ShareAvailability',
  RESPOND_TO_AVAILABILITY: 'RespondToAvailability',
  // Server → Client
  RECEIVE_MESSAGE: 'ReceiveMessage',
  UPDATE_UNREAD_COUNT: 'UpdateUnreadCount',
  OFFER_MADE: 'OfferMade',
  OFFER_ACCEPTED: 'OfferAccepted',
  OFFER_DECLINED: 'OfferDeclined',
  OFFER_COUNTERED: 'OfferCountered',
  OFFER_EXPIRED: 'OfferExpired',
  MEETING_PROPOSED: 'MeetingProposed',
  MEETING_ACCEPTED: 'MeetingAccepted',
  MEETING_DECLINED: 'MeetingDeclined',
  MEETING_RESCHEDULED: 'MeetingRescheduled',
  MEETING_EXPIRED: 'MeetingExpired',
  AVAILABILITY_SHARED: 'AvailabilityShared',
  AVAILABILITY_RESPONDED: 'AvailabilityResponded',
  AVAILABILITY_EXPIRED: 'AvailabilityExpired',
} as const;
