#!/bin/bash
export POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB JWT_KEY JWT_ISSUER JWT_AUDIENCE JWT_ACCESSTOKENEXPIRATIONMINUTES JWT_REFRESHTOKENEXPIRATIONDAYS VITE_APP_API_URL DOCKER_GITHUB_TOKEN GITHUB_REPOSITORY_OWNER MINIO_CONSOLE_URL MINIO_BUCKETNAME MINIO_PRESIGNEDURLEXPIRATIONHOURS MINIO_SERVERURL MINIO_ACCESSKEY MINIO_SECRETKEY

mkdir -p ~/automotive-marketplace

cat > ~/automotive-marketplace/.env << EOL
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
JWT_KEY=${JWT_KEY}
JWT_ISSUER=${JWT_ISSUER}
JWT_AUDIENCE=${JWT_AUDIENCE}
JWT_ACCESSTOKENEXPIRATIONMINUTES=${JWT_ACCESSTOKENEXPIRATIONMINUTES}
JWT_REFRESHTOKENEXPIRATIONDAYS=${JWT_REFRESHTOKENEXPIRATIONDAYS}
VITE_APP_API_URL=${VITE_APP_API_URL}
MINIO_CONSOLE_URL=${MINIO_CONSOLE_URL}
MINIO_BUCKETNAME=${MINIO_BUCKETNAME}
MINIO_PRESIGNEDURLEXPIRATIONHOURS=${MINIO_PRESIGNEDURLEXPIRATIONHOURS}
MINIO_SERVERURL=${MINIO_SERVERURL}
MINIO_ACCESSKEY=${MINIO_ACCESSKEY}
MINIO_SECRETKEY=${MINIO_SECRETKEY}
DOCKER_REGISTRY=ghcr.io/${GITHUB_REPOSITORY_OWNER}/
EOL

mkdir -p ~/automotive-marketplace/nginx/conf
mkdir -p ~/automotive-marketplace/nginx/logs

echo ${DOCKER_GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} --password-stdin

cd ~/automotive-marketplace
docker-compose pull
docker-compose down
docker-compose up -d