services:
  automotive.marketplace.server:
    image: ${DOCKER_REGISTRY}automotive.marketplace.server:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Production=Host=db;Port=5433;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    networks:
      - app-network
    restart: unless-stopped
  automotive.marketplace.client:
    image: ${DOCKER_REGISTRY}automotive.marketplace.client:latest
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    networks:
      - app-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - automotive.marketplace.server
      - automotive.marketplace.client
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: