services:
  automotive.marketplace.server:
    image: ${DOCKER_REGISTRY-}automotivemarketplaceserver
    build:
      context: .
      dockerfile: Automotive.Marketplace.Server/Dockerfile
  automotive.marketplace.client:
    image: ${DOCKER_REGISTRY-}automotivemarketplaceclient
    build:
      context: ./automotive-marketplace.client
      target: production
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: taurasbear
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: automotive_marketplace
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: