services:
  automotive.marketplace.server:
    build:
      target: base
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ./Automotive.Marketplace.Server:/app
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro 
    networks:
      - app-network
    depends_on:
      - db

  automotive.marketplace.client:
    image: ${DOCKER_REGISTRY-}automotive.marketplace.client:dev
    build:
      context: ./automotive.marketplace.client
      target: development
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://automotive.marketplace.server:8080
    ports:
      - "57263:57263"
    volumes:
      - ./automotive.marketplace.client:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - automotive.marketplace.server
  
  db:
    networks:
      - app-network

networks:
  app-network:
    driver: bridge