services:
  automotive.marketplace.server:
    image: automotive.marketplace.server:dev
    build:
      context: .
      dockerfile: ./Automotive.Marketplace.Server/Dockerfile
      target: dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - DOTNET_WATCH_SUPPRESS_EMOJIS=0
      - ConnectionStrings__DevDocker=${DEV_DOCKER_DB_CONNECTION_STRING}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    ports:
      - "8080"
      - "8081"
    volumes:
      - ./Automotive.Marketplace.Server:/app/Automotive.Marketplace.Server
      - ./Automotive.Marketplace.Application:/app/Automotive.Marketplace.Application
      - ./Automotive.Marketplace.Domain:/app/Automotive.Marketplace.Domain
      - ./Automotive.Marketplace.Infrastructure:/app/Automotive.Marketplace.Infrastructure
      - /app/Automotive.Marketplace.Server/bin
      - /app/Automotive.Marketplace.Server/obj
      - /app/Automotive.Marketplace.Application/bin
      - /app/Automotive.Marketplace.Application/obj
      - /app/Automotive.Marketplace.Domain/bin
      - /app/Automotive.Marketplace.Domain/obj
      - /app/Automotive.Marketplace.Infrastructure/bin
      - /app/Automotive.Marketplace.Infrastructure/obj
      - ${HOME}/Documents/.aspnet/https:/root/.aspnet/https:ro
    networks:
      - app-network
    depends_on:
      - db

  automotive.marketplace.client:
    image: automotive.marketplace.client:dev
    build:
      context: ./automotive.marketplace.client
      target: development
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://automotive.marketplace.server:8080
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "57263:57263"
    volumes:
      - ./automotive.marketplace.client:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - automotive.marketplace.server
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - db
  db:
    ports:
      - "5433:5433"
    networks:
      - app-network
  nginx:
    restart: no

networks:
  app-network:
    driver: bridge
volumes:
    pgadmin_data: