services:
  automotive.marketplace.server:
    image: ${DOCKER_REGISTRY-}automotive.marketplace.server
    build:
      context: .
      dockerfile: Automotive.Marketplace.Server/Dockerfile
  automotive.marketplace.client:
    image: ${DOCKER_REGISTRY-}automotive.marketplace.client
    build:
      context: ./automotive-marketplace.client
      target: production
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: taurasbear
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: automotive_marketplace
      PGPORT: 5433
    ports:
      - "5433:5433" # remove outside mapped port if necessary
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: