/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as VariantsRouteImport } from './app/routes/variants'
import { Route as RegisterRouteImport } from './app/routes/register'
import { Route as ModelsRouteImport } from './app/routes/models'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as ListingsRouteImport } from './app/routes/listings'
import { Route as InboxRouteImport } from './app/routes/inbox'
import { Route as AboutRouteImport } from './app/routes/about'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ListingCreateRouteImport } from './app/routes/listing/create'
import { Route as ListingIdRouteImport } from './app/routes/listing/$id'

const VariantsRoute = VariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingCreateRoute = ListingCreateRouteImport.update({
  id: '/listing/create',
  path: '/listing/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox': typeof InboxRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/register': typeof RegisterRoute
  '/variants': typeof VariantsRoute
  '/listing/$id': typeof ListingIdRoute
  '/listing/create': typeof ListingCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox': typeof InboxRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/register': typeof RegisterRoute
  '/variants': typeof VariantsRoute
  '/listing/$id': typeof ListingIdRoute
  '/listing/create': typeof ListingCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox': typeof InboxRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/register': typeof RegisterRoute
  '/variants': typeof VariantsRoute
  '/listing/$id': typeof ListingIdRoute
  '/listing/create': typeof ListingCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/inbox'
    | '/listings'
    | '/login'
    | '/models'
    | '/register'
    | '/variants'
    | '/listing/$id'
    | '/listing/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/inbox'
    | '/listings'
    | '/login'
    | '/models'
    | '/register'
    | '/variants'
    | '/listing/$id'
    | '/listing/create'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/inbox'
    | '/listings'
    | '/login'
    | '/models'
    | '/register'
    | '/variants'
    | '/listing/$id'
    | '/listing/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InboxRoute: typeof InboxRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  RegisterRoute: typeof RegisterRoute
  VariantsRoute: typeof VariantsRoute
  ListingIdRoute: typeof ListingIdRoute
  ListingCreateRoute: typeof ListingCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variants': {
      id: '/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof VariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/create': {
      id: '/listing/create'
      path: '/listing/create'
      fullPath: '/listing/create'
      preLoaderRoute: typeof ListingCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InboxRoute: InboxRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  RegisterRoute: RegisterRoute,
  VariantsRoute: VariantsRoute,
  ListingIdRoute: ListingIdRoute,
  ListingCreateRoute: ListingCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
