export type CreateListingCommand = {
  price: number;
  description?: string;
  colour?: string;
  vin?: string;
  powerKw?: number;
  engineSizeMl?: number;
  mileage: number;
  isSteeringWheelRight: boolean;
  modelId?: string;
  variantId?: string;
  city: string;
  isUsed: boolean;
  year?: number;
  transmissionId?: string;
  fuelId?: string;
  doorCount?: number;
  bodyTypeId?: string;
  drivetrainId: string;
  isCustom?: boolean;
  images: Blob[];
};
